apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
  labels:
    app: simple-app
  annotations:
    configmap.reloader.stakater.com/reload: app-config
    secret.reloader.stakater.com/reload: my-secret
spec:
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      volumes:
        - name: env-volume
          emptyDir: {}
      initContainers:
        - name: env-creator
          image: alpine
          command: ["/bin/sh", "-c", "env > /env/.env"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: my-secret
          volumeMounts:
            - name: env-volume
              mountPath: /env
      containers:
        - name: simple-app
          image: ghcr.io/vietnh2202/simple-app
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
          livenessProbe:
            httpGet:
              path: /healthz/liveness
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
