---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: simple-app-policy
spec:
  imageRepositoryRef:
    name: simple-app-image
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: "^preprod-(?P<timestamp>[0-9]+)-(.*)$"
    extract: "$timestamp"
