apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: simple-app
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: gitops-lab-app
  git:
    checkout:
      ref:
        branch: preprod
    commit:
      author:
        name: flux-bot
        email: flux-bot@users.noreply.github.com
      messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: preprod
  update:
    path: ./kustomize/preprod/simple-app
    strategy: Setters
