apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  MY_SECRET: czNjcjN0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NAME: "Website"
  TEAM: "DevOps team"
