apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  MY_SECRET: echo -n "s3cr3t" | base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NAME: Website
